### ISSUE TITLE
下载指定作品时报错

### ISSUE THREAD

**Issue by Clementine66peter** [Ljzd-PRO/KToolBox#180]
使用ktoolbox download-post下载单个作品的时候，会报错TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'，这是由于什么原因？之前都没有这样的问题。
ktoolbox sync-creator则不会报错，能够完整下载

**Comment by Ljzd-PRO** [comment]
有具体日志吗？也就是日志显示在哪个代码区域报错的

**Comment by Clementine66peter** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Scripts\ktoolbox.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ktoolbox\__main__.py", line 14, in main
    fire.Fire(KToolBoxCli)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ktoolbox\cli.py", line 175, in download_post
    post_path = path / generate_post_path_name(ret.data)
                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'WindowsPath' and 'NoneType'

**Comment by Ljzd-PRO** [comment]
目前看不出有什么问题，使用的完整的命令是什么呢，以及如果有设置了配置，也发一下配置内容。另外也可以试试最新的版本。
